name: deploy_to_server

on:
  push:
    branches:
      - n-master
  pull_request:
    branches:
      - n-master

jobs:

  # deploy to server
  deploy_to_server:
    runs-on: ubuntu-latest
    needs: [pnpm_install, report, lint, typecheck, unit, test, validate-api-json, vitest, e2e-back, e2e-front]
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        # passphrase: ${{ secrets.SSH_PASSPHRASE }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          curl -X POST -H "Content-Type: application/json" -d '{"i": "${{ secrets.ACCT_TOKEN }}", "text": "@n1lsqn@papi.n1l.dev アップデートを開始しました。 `${{ github.head_ref }}`", "visibility": "home"}' https://m.n1l.dev/api/notes/create
          cd /home/misskey/misskey
          git pull origin
          git fetch origin
          git reset --hard origin/${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git submodule update --init
          NODE_ENV=production pnpm install --frozen-lockfile
          NODE_ENV=production pnpm run build
          pnpm run migrate
          sudo service misskey restart
          sleep 60
          curl -X POST -H "Content-Type: application/json" -d '{"i": "${{ secrets.ACCT_TOKEN }}", "text": "@n1lsqn@papi.n1l.dev アップデートを完了しました。 `${{ github.head_ref }}`", "visibility": "home"}' https://m.n1l.dev/api/notes/create
