name: deploy_to_server
on:
  workflow_run:
    workflows:
      - Lint
      - Test (backend)
      - Test (frontend)
    types:
      - completed
jobs:
  check_suite:
    runs-on: ubuntu-latest
    outputs:
      all_success: ${{ steps.check.outputs.all_success }}
    steps:
      - name: Check workflow conclusions
        id: check
        run: |
          workflows=("Lint" "Test (backend)" "Test (frontend)")
          all_success=true
          for workflow in "${workflows[@]}"; do
            status=$(gh run list --workflow="$workflow" --json conclusion --jq '.[0].conclusion')
            if [ "$status" != "success" ]; then
              all_success=false
              break
            fi
          done
          echo "all_success=$all_success" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy_to_server:
    needs: check_suite
    runs-on: ubuntu-latest
    if: ${{ needs.check_suite.outputs.all_success == 'true' }}
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          curl -X POST -H "Content-Type: application/json" -d '{"i": "${{ secrets.ACCT_TOKEN }}", "text": "@n1lsqn@papi.n1l.dev アップデートを開始しました。 `${{ github.head_ref }}`", "visibility": "home"}' https://m.n1l.dev/api/notes/create
          cd /home/misskey/misskey
          git pull origin
          git fetch origin
          git reset --hard origin/${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git submodule update --init
          NODE_ENV=production pnpm install --frozen-lockfile
          NODE_ENV=production pnpm run build
          pnpm run migrate
          sudo service misskey restart
