name: Lint

on:
  push:
    paths:
      - locales/**
      - .github/workflows/locale.yml
  pull_request:
    paths:
      - locales/**
      - .github/workflows/locale.yml
jobs:
  locale_verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        submodules: true
    - uses: pnpm/action-setup@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - run: cd locales && node verify.js
